### ISSUE TITLE
Question about the 3.0 version and .py files

### ISSUE THREAD

**Issue by IamJanS** [ginkage/MHI-AC-Ctrl-ESPHome#101]
Hi,

I'm currently using the code from absalom-muc to control my ACs. I'm using ESPhome from the command line and run Home Assistent in a container. I'm looking to start using this project (it adds some improvements) but I have some questions. I don't get what is meant by: "Manually downloading the files to your Home Assistant setup is no longer needed" as mentioned with the 3.0 version. Also I don't get the .py files that are included. Maybe I'm asking something very stupid but I hope someone can explain. 

Best regards,

Jan

**Comment by Dennis-Q** [comment]
Hi Jan,

You need ESPHome running and with the container-installation I don't think you can install Add-ons easily (my knowledge might be somewhat outdated). Sure, you can still run ESPHome in a separate container.

Then, regarding the download. Before you had to manually download a folder and some files and put the ESPHome folder where you configs are stored. This isn't needed anymore with the latest change as with the 'external_components' function of ESPHome it is done for you. This makes setup a lot easier as you only need to copy/paste the ESPHome yaml example from this github, change a few values and you can start building/installing.

So the .py and other files in the subdir of this repo are automatically downloaded and you can ignore those; you don't need to download, view or change them manually.
