### ISSUE TITLE
Fan modes don't seem to correlate to real fan mode

### ISSUE THREAD

**Issue by tharealmb** [ginkage/MHI-AC-Ctrl-ESPHome#22]
Right now there are 4 fan modes: Low, Medium, High, Auto

But the remote (SKR-ZSX at least) has 5 fan modes: Ultra-low, Low, Medium, High, Auto

Right now it seems that 
(ESP = AC)
Low=Ultra-low
Medium=Low
High=Medium
Auto= High

So, Auto doesn't work (and i don't know if that is possible) and is actually putting the AC at the High fan mode. 

It seems that Ultra-low should be added if possible and Auto should be renamed to High.
I'd love to have Auto or 3D Auto as options, but i don't know if that is actually possible and i'm definitely not a programmer.

**Comment by serrj-sv** [comment]
> So, Auto doesn't work (and i don't know if that is possible) and is actually putting the AC at the High fan mode.

"Fan auto is not supported via the SPI":
https://github.com/absalom-muc/MHI-AC-Ctrl/blob/master/SW-Configuration.md

> I'd love to have Auto or 3D Auto as options, but i don't know if that is actually possible

not possible (unless someone discover proprietary undocumented  SPI commands for this)

**Comment by stosoorok** [comment]
If you use Home Assistant, you can rename it in Lovelace card.
https://github.com/absalom-muc/MHI-AC-Ctrl/issues/97#issuecomment-1167506725

**Comment by smennie** [comment]
I've set it up to use Diffuse, Low, Medium, High and Auto. This way HA and the remote will show the same mode and I get control of all 4+Auto fan speeds from HA
I just add CLIMATE_FAN_DIFFUSE in the fan speed and status sections and reshuffle the numbers and add CLIMATE_FAN_DIFFUSE to the traits.set_supported_fan_modes
I've been using this setup in an older release for over a year and it seems to work well.

**Comment by ervee** [comment]
I think this is great! Bit I'm not 100÷ sure how to do this too. Is this all done in the ESPHome yaml? Could you please put this in a pull request so we can all benefit from this please 🙏

**Comment by RobertJansen1** [comment]
should now be fixed in master :)

**Comment by smennie** [comment]
> should now be fixed in master :)

Looking good, but I had it ordered like this so that Diffuse was slowest, which makes sense in my brain.

            case 0:
                this->fan_mode = climate::CLIMATE_FAN_DIFFUSE;
                break;
            case 1:
                this->fan_mode = climate::CLIMATE_FAN_LOW;
                break;
            case 2:
                this->fan_mode = climate::CLIMATE_FAN_MEDIUM;
                break;
            case 6:
                this->fan_mode = climate::CLIMATE_FAN_HIGH;
                break;
            case 7:
                this->fan_mode = climate::CLIMATE_FAN_AUTO;
                break;

**Comment by mauriceazrak** [comment]
Bonjour tout le monde.
J'ai installé l' ESP D1 mini et téléchargé le fichier yaml, placé les dossier dans le dossier ESPHOME......
connecté l'appareil dans le climatiseur, les commandes apparaissent dasn Home Assistant, mais aucune commande ne se fait.
voici le log du fichier, si quelqu'un peut m'expliquer ce qu'il se passe ..... ce serait très sympatique.
[logs_lr_mhi_ac_ctrl_logs.txt](https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/files/12751936/logs_lr_mhi_ac_ctrl_logs.txt)

**Comment by RobertJansen1** [comment]
> > should now be fixed in master :)
> 
> Looking good, but I had it ordered like this so that Diffuse was slowest, which makes sense in my brain.
> 
> ```
>         case 0:
>             this->fan_mode = climate::CLIMATE_FAN_DIFFUSE;
>             break;
>         case 1:
>             this->fan_mode = climate::CLIMATE_FAN_LOW;
>             break;
>         case 2:
>             this->fan_mode = climate::CLIMATE_FAN_MEDIUM;
>             break;
>         case 6:
>             this->fan_mode = climate::CLIMATE_FAN_HIGH;
>             break;
>         case 7:
>             this->fan_mode = climate::CLIMATE_FAN_AUTO;
>             break;
> ```

I don;t know how this order is achieved to be honest, i would realy like it to be like this but the cases are not the order it is displayed I think.
