### ISSUE TITLE
Vanes control question

### ISSUE THREAD

**Issue by ervee** [ginkage/MHI-AC-Ctrl-ESPHome#25]
Hi,

I'm not sure if I'm doing anything wrong or if this is a limitation of using Home Assistant with ESPHome instead of working with the MQTT stuff in the original absalom-muc project, but I'm not able to control the vane (up/down) position.

I can set a swing mode to "off" or "vertical" and this kind of works:
![image](https://user-images.githubusercontent.com/4435930/176207353-d129a4a8-77c2-49c8-90af-0e3336600f9f.png)

Swing does swing, but "off" always sets the vane to the upmost position.

I see in MHI-AC-Ctrl-core.h
https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/blob/b5ae9cb5ce968873e088f4703146593bfa7e9ba9/MHI-AC-Ctrl-core.h#L83
There are 4 positions and swing to work with.

And in the absalom-muc project there is a screenshot of vane control:
![image](https://user-images.githubusercontent.com/4435930/176208857-796c8b1b-8da5-4771-9b09-ef06deb7edc0.png)

Is it possible to get this in Home Assistant with ESPHome?

Greetings,
Ralf.

**Comment by jeroenkl** [comment]
Same question

**Comment by jeroenkl** [comment]
@ginkage could you please help?

**Comment by ginkage** [comment]
Sorry, no idea... I'm guessing it's a limitation of ESPHome, but can't tell for sure.
Unfortunately, due to the war in Ukraine, I don't have access to my AC unit, and won't be able to test anything for a while...

**Comment by ervee** [comment]
This is fixed by pull #38 !

**Comment by serrj-sv** [comment]
> This is fixed by pull #38 !

Another take on vanes control: https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/pull/62
