### ISSUE TITLE
Power Status always on on reboot

### ISSUE THREAD

**Issue by aferrato** [ginkage/MHI-AC-Ctrl-ESPHome#30]
Hello,
when the esp8266 is rebooted, the status of the air conditioner changes to on with the last mode used even if it is actually off.

I have tried what is written here  #2, but it doesn't work.

To solve I added this code:

```
switch (this-> power_) {
     case 0:
         this-> mode = climate :: CLIMATE_MODE_OFF;
         this-> publish_state ();
         break;
     default:
         break;
 }
```

inside `void cbiStatusFunction (ACStatus status, int value) override` before `switch (status)`

**Comment by ervee** [comment]
I have this too. Will give your solution a try.

**Comment by sanderlv** [comment]
Like this works indeed!
![image](https://user-images.githubusercontent.com/16528916/194420756-922ab84a-c43b-446b-904d-3ff3cad8c06c.png)

**Comment by ginkage** [comment]
I've committed this workaround: https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/commit/a43bc7187dba3ea520b662487ad94af0bdf9fdfb
Please check if it works correctly.

**Comment by sanderlv** [comment]
I can confirm it works, thanks!
