### ISSUE TITLE
(Default) update_interval?

### ISSUE THREAD

**Issue by sanderlv** [ginkage/MHI-AC-Ctrl-ESPHome#45]
what is the (default)update_interval for:

https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/blob/28f24b21d49cc9d9b863cc5d5d91155dbff70fc7/lr_mhi_ac_ctrl.yaml#L76-L92

**Comment by synegic** [comment]
I think this is better asked on the core library git. But AFAIK it only updates when the AC unit sends a SPI frame containing new data. You can watch it come in (and maybe time it yourself) by looking in the logs of your ESPHome device. No tweaking possible on this interval afaik.
