### ISSUE TITLE
Error's compiling ESPHome

### ISSUE THREAD

**Issue by I-Lynx** [ginkage/MHI-AC-Ctrl-ESPHome#5]
Hi,

I get these errors while compiling in ESPhome:

In file included from src/main.cpp:10:0:
src/mhi_ac_ctrl.h: In member function 'virtual esphome::climate::ClimateTraits MhiAcCtrl::traits()':
src/mhi_ac_ctrl.h:352:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supported_modes'
         traits.set_supported_modes({ CLIMATE_MODE_AUTO, CLIMATE_MODE_COOL, CLIMATE_MODE_HEAT, CLIMATE_MODE_DRY, CLIMATE_MODE_FAN_ONLY });
                ^
In file included from src/main.cpp:10:0:
src/mhi_ac_ctrl.h:354:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supported_presets'
         traits.set_supported_presets({ CLIMATE_PRESET_NONE });
                ^
src/mhi_ac_ctrl.h:354:40: error: 'CLIMATE_PRESET_NONE' was not declared in this scope
         traits.set_supported_presets({ CLIMATE_PRESET_NONE });
                                        ^
src/mhi_ac_ctrl.h:358:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supported_fan_modes'
         traits.set_supported_fan_modes({ CLIMATE_FAN_AUTO, CLIMATE_FAN_LOW, CLIMATE_FAN_MEDIUM, CLIMATE_FAN_HIGH });
                ^
src/mhi_ac_ctrl.h:359:16: error: 'class esphome::climate::ClimateTraits' has no member named 'set_supported_swing_modes'
         traits.set_supported_swing_modes({ CLIMATE_SWING_OFF, CLIMATE_SWING_BOTH, CLIMATE_SWING_VERTICAL, CLIMATE_SWING_HORIZONTAL });
                ^
*** [/data/airco/.pioenvs/airco/src/main.cpp.o] Error 1
========================== [FAILED] Took 5.34 seconds ==========================

Add-on version: 1.16.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.1  (amd64 / qemux86-64)
 Home Assistant Core: 2021.6.6
 Home Assistant Supervisor: 2021.06.6

**Comment by ginkage** [comment]
You're using ESPHome 1.16.2, please upgrade to 1.19.4.
