### ISSUE TITLE
Home Assistant 2023.7 requires a setting to make service calls from ESPHome

### ISSUE THREAD

**Issue by ervee** [ginkage/MHI-AC-Ctrl-ESPHome#59]
With pull https://github.com/home-assistant/core/pull/95143 for Home Assistant 2023.7, they now require a setting per ESPHome device to allow service calls.

In lr_mhi_ac_ctrl.yaml you use a call to set_api_room_temperature.
So in case anyone uses this for new devices starting Home Assistant 2023.7 you need to enable the ESP device to make the service call.
![image](https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/assets/4435930/1c4fb212-7a88-48b1-807e-2216e3f46ef4)

Perhaps update the yaml example and/or the main README with a note?

**Comment by arpiecodes** [comment]
As far as I understand this new feature, it's for calling services from devices, not from HA. The `set_api_room_temperature` is actually a service exposed by the device, not HA. So this option does not have to be enabled for the 'use case' to update room temp from HA.

**Comment by JoepWi** [comment]
I can confirm that set_api_room_temperature just works fine.
As @arpiecodes states. The new functionality had to do with info going back from devices as an answer to specific HA call.

**Comment by ervee** [comment]
Great. Thanks for the confirmation!

**Comment by ervee** [comment]
Close

**Comment by ervee** [comment]
Woops
