### ISSUE TITLE
MHI-AC-Ctrl working MQTT communication with SRK 63 ZR, but MHI-AC-Ctrl-ESPHome does not show any communication

### ISSUE THREAD

**Issue by the-master006** [ginkage/MHI-AC-Ctrl-ESPHome#60]
I tried first to run my SRK 63 ZR with the D1 Wemos with MHI-AC-Ctrl-ESPHome, this does nothing besides connecting with Wifi. I flashed this via the python interface from ESPHome. 
Afterwards I tried to flash the D1 Wemos with the original MHI-AC-Ctrl project and then I can clearly see the MQTT communication working in the MQTT explorer.

What is going wrong? I saw somewhere in the files that it includes arduino.h, but I did not put that file in the directory, might that be the issue? Or anything else?
See attached the MQTT communication from the MHI-AC-Ctrl program.
Thanks!
<img width="285" alt="image" src="https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/assets/65864740/905f3aca-0a03-4b63-8154-b97bcf9bf93d">

**Comment by the-master006** [comment]
Any feedback?

**Comment by RobertJansen1** [comment]
what is the content of your esphome yaml file? did you include:
esphome:
  includes:
    - mhi_ac_ctrl.h
    - MHI-AC-Ctrl-core.h
    - MHI-AC-Ctrl-core.cpp

**Comment by the-master006** [comment]
Ok, thanks for your answer. I will check!
