### ISSUE TITLE
How to flash for a newbie

### ISSUE THREAD

**Issue by elrosso2** [ginkage/MHI-AC-Ctrl-ESPHome#72]
Maybe its clear to everyone. But how to actualy "flash" the files?

I placed the files in the ESPhome folder but what's next? My ESP8266 module is "online" after adding in ESPhome. But I can not find the Airco controls in my dashboard.

Thanks for the help!

**Comment by coyote1** [comment]
Open a terminal, go to the folder you placed the files.
Enter: esphome run lr_mhi_ac_ctrl.yaml
now it should flash your esp

**Comment by elrosso2** [comment]
Thanks for the help!

**Comment by RobertJansen1** [comment]
relates to #55 we hope to make this easier in the future, but making it easier is a bit complex :) based on your comment, i assume you figured it out and it is now working
