### ISSUE TITLE
Node not available after flashing

### ISSUE THREAD

**Issue by hjkoster400d** [ginkage/MHI-AC-Ctrl-ESPHome#8]
Hi, 

First of all, thank you for this easy implementation of the heatpump API using ESPHome. 
I placed the 3 .cpp/.h files in the root of the ESPHome directory of my HA instance, configured the yaml as described. But after flashing the interface returns this message:

![image](https://user-images.githubusercontent.com/7768158/124982465-05cbd680-e037-11eb-9d8e-dd935e5274c9.png)

Is this expected or did i do something wrong?

Also, the climate entity does not show up in homeassistant. 
Any idea what this could be?

Thanks for now

**Comment by ginkage** [comment]
Hi!
Thank you for the feedback.
Please note that you need to actually plug it into the A/C, otherwise it won't run.
If you just want to kick the tires a bit, you can comment out the lines with "mhi_ac_ctrl_core" in mhi_ac_ctrl.h (e.g. 30, 31, 36-38), and it will start without being plugged in.

**Comment by hjkoster400d** [comment]
Ah great, i was just trying to get the software running before plugging it into the AC. Thx for the quick feedback and trouble shooting. So if i'm correct, the climate entity will popup in homeassistant when the wemos is connected to the AC?

**Comment by ginkage** [comment]
Yes, it will also show up if you comment the actual control code as I've described above, in case you want to test how it works before you plug it in. Note that you may need to set up ESPHome integration or use HA's discovery feature.

**Comment by hjkoster400d** [comment]
Nice, thank you
