### ISSUE TITLE
[Feature Request] Hi-Power / Eco modes

### ISSUE THREAD

**Issue by EvoSems** [ginkage/MHI-AC-Ctrl-ESPHome#80]
Hi. I like to use eco mode at night and occasionally Hi power modes during the day.

**Comment by RobertJansen1** [comment]
there is no known way yet to send these codes to the unit through the SPI bus. see https://github.com/absalom-muc/MHI-AC-Ctrl/issues/126 for more information. Within your home automation it might be possible to achieve the same result. if it is discovered to be possible through the SPI, you are welcome to reopen the request
