### ISSUE TITLE
ATOMS3 LITE

### ISSUE THREAD

**Issue by Marc911H** [ginkage/MHI-AC-Ctrl-ESPHome#89]
Hello,

I am looking to use ATOMS3 LITE which are ESP32 S3.
after looking at this project https://github.com/gekkekoe/esphome-ecodan-hp/ which is made for MHI ecodan heat pump

Do you know what I need to adapt ?
 
I don't know about the pin

#define SCK_PIN  18
#define MOSI_PIN 23
#define MISO_PIN 19

For the moment I have : 

13:11:40	[W]	[mhi_ac_ctrl:143]     mhi_ac_ctrl_core.loop error: -3
13:11:40	[W]	[component:237]	Component <unknown> took a long time for an operation (102 ms).
13:11:40	[W]	[component:238]	Components should block for at most 30 ms.

**Comment by arpiecodes** [comment]
@Marc911H what are you trying to do? The Ecodan seems to be a whole different product line. That's not going to work with this project.
