### ISSUE TITLE
OTA platform config missing - breaking change since 2024.6.0

### ISSUE THREAD

**Issue by heino42** [ginkage/MHI-AC-Ctrl-ESPHome#93]
Dear all,
as described in [here](https://esphome.io/changelog/2024.6.0.html#ota-platforms), the 
ota:
section now also needs a platform entry, otherwise compilation will fail.

# New
ota:
  platform: esphome

Please update the YAML.

**Comment by RobertJansen1** [comment]
https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/commit/fd4850a6187451d1e78a4661a769c0ffa623e46d
fixed :)

**Comment by heino42** [comment]
Wow, that was quick - Thanks!
